// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260309155246_InitialDatabase")]
    partial class InitialDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.SMT_CauTrucDe", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<DateTime>("created_time")
                        .HasColumnType("datetime2");

                    b.Property<long>("created_user_id")
                        .HasColumnType("bigint");

                    b.Property<int>("duration")
                        .HasColumnType("int");

                    b.Property<long>("id_he")
                        .HasColumnType("bigint");

                    b.Property<long>("id_kieuhienthi")
                        .HasColumnType("bigint");

                    b.Property<long>("id_maudethi")
                        .HasColumnType("bigint");

                    b.Property<long>("id_mon")
                        .HasColumnType("bigint");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("bit");

                    b.Property<bool>("is_dungtailieu")
                        .HasColumnType("bit");

                    b.Property<bool>("is_trondethi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("last_modified_times")
                        .HasColumnType("datetime2");

                    b.Property<long?>("last_modified_user_id")
                        .HasColumnType("bigint");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("order")
                        .HasColumnType("int");

                    b.Property<int>("so_cau_hoi")
                        .HasColumnType("int");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("SMT_CauTrucDe");
                });

            modelBuilder.Entity("backend.Models.SMT_CauTrucDe_ThanhPhan", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<decimal>("coefficient")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("created_time")
                        .HasColumnType("datetime2");

                    b.Property<long>("created_user_id")
                        .HasColumnType("bigint");

                    b.Property<long>("id_cautrucde")
                        .HasColumnType("bigint");

                    b.Property<bool>("is_fixed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("last_modified_times")
                        .HasColumnType("datetime2");

                    b.Property<long?>("last_modified_user_id")
                        .HasColumnType("bigint");

                    b.Property<string>("note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("order")
                        .HasColumnType("int");

                    b.Property<int>("so_cau_hoi")
                        .HasColumnType("int");

                    b.Property<int>("total_question")
                        .HasColumnType("int");

                    b.Property<decimal>("total_score")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("type_answer")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("id_cautrucde");

                    b.ToTable("SMT_CauTrucDe_ThanhPhan");
                });

            modelBuilder.Entity("backend.Models.SMT_CauTrucDe_ThanhPhan_Sub", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<DateTime>("created_time")
                        .HasColumnType("datetime2");

                    b.Property<long>("created_user_id")
                        .HasColumnType("bigint");

                    b.Property<long>("id_cautrucde_thanhphan")
                        .HasColumnType("bigint");

                    b.Property<long>("id_chude")
                        .HasColumnType("bigint");

                    b.Property<long>("id_mucdo")
                        .HasColumnType("bigint");

                    b.Property<long>("id_nhomcauhoi")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("last_modified_times")
                        .HasColumnType("datetime2");

                    b.Property<long?>("last_modified_user_id")
                        .HasColumnType("bigint");

                    b.Property<int>("order")
                        .HasColumnType("int");

                    b.Property<int>("so_cau")
                        .HasColumnType("int");

                    b.Property<string>("ten_chude")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ten_muc_tri_nang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("total_question")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("id_cautrucde_thanhphan");

                    b.ToTable("SMT_CauTrucDe_ThanhPhan_Sub");
                });

            modelBuilder.Entity("backend.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("backend.Models.SMT_CauTrucDe_ThanhPhan", b =>
                {
                    b.HasOne("backend.Models.SMT_CauTrucDe", "CauTrucDe")
                        .WithMany("ThanhPhans")
                        .HasForeignKey("id_cautrucde")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CauTrucDe");
                });

            modelBuilder.Entity("backend.Models.SMT_CauTrucDe_ThanhPhan_Sub", b =>
                {
                    b.HasOne("backend.Models.SMT_CauTrucDe_ThanhPhan", "ThanhPhan")
                        .WithMany("Subs")
                        .HasForeignKey("id_cautrucde_thanhphan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ThanhPhan");
                });

            modelBuilder.Entity("backend.Models.SMT_CauTrucDe", b =>
                {
                    b.Navigation("ThanhPhans");
                });

            modelBuilder.Entity("backend.Models.SMT_CauTrucDe_ThanhPhan", b =>
                {
                    b.Navigation("Subs");
                });
#pragma warning restore 612, 618
        }
    }
}
